modLoader="javafml" #mandatory
loaderVersion="[37,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="MIT"
issueTrackerURL="https://github.com/RaphGamingz/RAM/issues" #optional
[[mods]] #mandatory
modId="ram" #mandatory
version="${file.jarVersion" #mandatory
displayName="RAM Mod" #mandatory
updateJSONURL="https://github.com/RaphGamingz/RAM/blob/main/update.json" #optional
displayURL="https://github.com/RaphGamingz/RAM" #optional
logoFile="rammod.png" #optional
credits="Thanks to raph for creating this mod" #optional
authors="Raph" #optional
description='''
A mod made by Raph
He has sadly forgotten what the acronym RAM stands for
Have fun playing with this mod
'''

[[dependencies.ram]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[37,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.ram]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1,1.18)"
    ordering="NONE"
    side="BOTH"